# Generated by Django 4.1.12 on 2023-12-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
    ]
